version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  db_data:

networks:
  postgres_network:
